# Generated by Django 2.2.6 on 2019-10-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='street',
            new_name='street_address',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='street_no',
        ),
    ]
