# Generated by Django 2.2.6 on 2019-10-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_auto_20191024_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='user_id',
            new_name='user_name',
        ),
    ]
