# Generated by Django 2.2.6 on 2019-10-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_auto_20191024_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='user_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
