# Generated by Django 2.2.6 on 2019-10-28 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_auto_20191028_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='first_name',
            new_name='firstName',
        ),
    ]
