# Generated by Django 2.2.6 on 2019-10-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0010_auto_20191028_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='city',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='firstName',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='lastName',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='streetAddress',
            field=models.CharField(max_length=120),
        ),
    ]
