# Generated by Django 2.2.6 on 2019-10-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0011_auto_20191028_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='buyerId',
            field=models.IntegerField(blank=True, default=55555),
            preserve_default=False,
        ),
    ]
