# Generated by Django 2.2.6 on 2019-10-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
